language: csharp
solution: Wavefront-CSharp-SDK.sln
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test Wavefront.CSharp.SDK.Test/Wavefront.CSharp.SDK.Test.csproj
