language: csharp
solution: Wavefront.SDK.CSharp.sln
mono: none
dist: bionic
dotnet: 2.2

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test Wavefront.SDK.CSharp.Test/Wavefront.SDK.CSharp.Test.csproj
